rm -rf dirPassenger
rm -rf dirPilot
rm -rf dirHostess
rm -rf dirPlane
rm -rf dirDestinationAirport
rm -rf dirDepartureAirport
rm -rf dirGeneralRepos
rm -rf dirRegistry
rm -rf dirRMIRegistry

rm -rf dirPassenger.zip
rm -rf dirPilot.zip
rm -rf dirHostess.zip
rm -rf dirPlane.zip
rm -rf dirDestinationAirport.zip
rm -rf dirDepartureAirport.zip
rm -rf dirGeneralRepos.zip
rm -rf dirRegistry.zip
rm -rf dirRMIRegistry.zip